apiVersion: v1
kind: Service
metadata:
  name: cluster-svc
  labels:
    env: demo
spec:
  ports:
    - port: 80
  selector:
    env: demo

---
# kubeclt create service clusterip my-service --tcp=80:8080 --dry-run=client -o yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
  creationTimestamp: null
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-service
status:
  loadBalancer: {}

---
# kubectl create service clusterip my-service --tcp=80:8080 --dry-run=server
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
  namespace: default
  uid: 1234567890
  creationTimestamp: 2021-01-01T00:00:00Z
spec:
  clusterIP: 10.96.0.10
  clusterIPs:
    - 10.96.0.0
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-service
  sessionAffinity: None
  type: ClusterIP
