# Opaque Secrets: User-defined
#kubectl create secret generic <secret-name> --from-literal=password=<your-password>

apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: app-container
      image: busybox:1.28
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password

# docker-registry-secret
# kubectl create secret docker-registry sample-docker-secret \
# --docker-email=sample@example.com \ --docker-username=scott \
# --docker-password=tiger \ --docker-server=my-registry.example:5000
