# kubectl create deploy affinity-pod --image=nginx:latest --dry-run=client -o yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis-3
spec:
  containers:
    - image: redis
      name: redis
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "disktype"
                operator: In
                values:
                  - "ssd"

---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
spec:
  containers:
    - name: affinity-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "topology.kubernetes.io/region"
                operator: In
                values:
                  - "chh-dk-2"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: "disktype"
                operator: In
                values:
                  - "ssd"
