apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: prod
    type: frontend
    tier: web
    app: my-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

# kubectl get pods --selector tier=web
